### ISSUE TITLE
Exception: JNI: Init'd AndroidJavaClass with null ptr!

### ISSUE THREAD

**Issue by fishkingsin** [jpush/jpush-unity3d-plugin#12]
using(AndroidJavaClass jpushClass = new AndroidJavaClass("com.example.unity3d_jpush_demo.JPushBridge"))
step to reproduce 
1. Create new project 
2. import plugin
3. update AndroidManifest.xml package id 
4. add Game object in Scene, add JPushBridge to component
5. build and run android
6. error occure

**Comment by lhw5123** [comment]
Did you run on a real device?

**Comment by fishkingsin** [comment]
Yes I am running on real device

**Comment by fishkingsin** [comment]
Does "com.example.xxxxxxx" affect ?

**Comment by fishkingsin** [comment]
commented static init , no crash , but unable to receive push message

```
static JPushBinding()
		{
//			using(AndroidJavaClass jpushClass = new AndroidJavaClass("com.example.unity3d_jpush_demo.JPushBridge"))
//			{
//				_plugin = jpushClass.CallStatic<AndroidJavaObject>("getInstance");
//			}
		}
		void Start(){
			using(AndroidJavaClass jpushClass = new AndroidJavaClass("com.example.unity3d_jpush_demo.JPushBridge"))
			{
				_plugin = jpushClass.CallStatic<AndroidJavaObject>("getInstance");
			}
		}

		public static void setDebug(bool debug)
		{
			if (_plugin == null) {
				using(AndroidJavaClass jpushClass = new AndroidJavaClass("com.example.unity3d_jpush_demo.JPushBridge"))
				{
					_plugin = jpushClass.CallStatic<AndroidJavaObject>("getInstance");
				}
			}
			_plugin.Call("setDebug", debug);
		}

```

**Comment by fishkingsin** [comment]
solved 
currently, i work for both ios and android platform 

first, i follow the instruction of ios 
when it was done, I tried to migrate to Android and I thought  JPushBinder has to add to Game Object like ios did. but ti cause crash , I need to remove JPush binder from Gameobject and add other Script to init JPushBinder
