### ISSUE TITLE
库按教程添加了，编译还是报错

### ISSUE THREAD

**Issue by huqiang0204** [jpush/jpush-unity3d-plugin#17]
Undefined symbols for architecture arm64:
  "_g_typeDefinitionSize3800", referenced from:
      _g_Il2CppTypeDefinitionSizesTable in Il2CppCompilerCalculateTypeValuesTable.o
  "_g_typeDefinitionSize3801", referenced from:
      _g_Il2CppTypeDefinitionSizesTable in Il2CppCompilerCalculateTypeValuesTable.o

**Comment by huangminlinux** [comment]
看日志不像是我们的插件。

**Comment by huqiang0204** [comment]
嗯，和另外一个插件一起用就这样了uniwebview

**Comment by zhangdaixing** [comment]
AndroidManifest 文件导入unity ,如果有相同文件会被替换，这个文件不要导入，最后直接拖到unity
