### ISSUE TITLE
安卓上跑了闪退

### ISSUE THREAD

**Issue by yappy1985** [jpush/jpush-unity3d-plugin#18]
下载jpush unity 3.1.4，倒入unity5.6.2f1，android manifest手动倒入，添加一个JPush GameObject，JPush.JPushBinding.Init("JPush");，打包成apk。在安卓上安装正常，开启跑，过了splash后，直接闪退。请大神帮帮忙，不知道哪里出了问题。附件是用的manifest
[AndroidManifest_copy.txt](https://github.com/jpush/jpush-unity3d-plugin/files/1659171/AndroidManifest_copy.txt)

**Comment by lhw5123** [comment]
你应用的包名是 `com.test.test`，还是 `com.unity3d.player`。AndroidManifest.xml 里的包名不一致。
另外，有没有日志？

**Comment by yappy1985** [comment]
哦哦，我改改看看。
怎么读取日志啊？用的android studio

**Comment by yappy1985** [comment]
把com.unity3d.player改成了com.test.test，还是过了splash后闪退

**Comment by lhw5123** [comment]
还是贴下闪退时的日志吧。用 Android Studio 打开 Logcat 窗口可以看。

**Comment by yappy1985** [comment]
看到日志了。一下是日志。还没有倒入jpush unity package 之前都是正常可以跑的。一下2行是报错

01-26 22:20:27.204 3733-3747/? E/Unity: Unable to find AudioPluginOculusSpatializer
01-26 22:20:27.205 3733-3747/? E/Unity: Unable to find libAudioPluginOculusSpatializer

**Comment by yappy1985** [comment]
看到日志了。一下是日志。还没有倒入jpush unity package 之前都是正常可以跑的。附件是报错.

[logcat2.pdf](https://github.com/jpush/jpush-unity3d-plugin/files/1668480/logcat2.pdf)

**Comment by lhw5123** [comment]
你发的这个日志，搜索了下没找到 JPush 的相关内容啊。我这边把插件 Android 部分改成了 .aar 的形式，你再试下呢。
另外日志可以就贴一下闪退时的错误信息（是红色的），PDF 不太方便看。

**Comment by yappy1985** [comment]
好的，明天试试

**Comment by yappy1985** [comment]
试了倒入unity package v3.2.0。打包apk的时候有这个报错。api 19太高了，还有很多手机还在旧的版本，有办法挑到大概api 9吗？

~/Temp/StagingArea/AndroidManifest-main.xml:94:3-71 Error:
	uses-sdk:minSdkVersion 9 cannot be smaller than version 19 declared in library ~/Temp/StagingArea/android-libraries/jpush/AndroidManifest.xml as the library might be using APIs not available in 9
	Suggestion: use a compatible library with a minSdk of at most 9,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="cn.jiguang.unity.push" to force usage (may lead to runtime failures)

UnityEditor.HostView:OnGUI()

**Comment by lhw5123** [comment]
... API 9 是 Android 2.3。现在还用 Android 2.3 的手机也玩不了游戏了吧。
主要，API 低于 14 的应用，今年下半年开始就可能上架不了 Google Play 了。
最低我给你改到 14 吧，但个人建议 Android 4.4 以下的手机，其实都不用管了，不仅占比已经非常低了，兼容起来还麻烦。。
