### ISSUE TITLE
SetAlias返回错误码6002

### ISSUE THREAD

**Issue by nikki-nn4** [jpush/jpush-unity3d-plugin#29]
我刚开始接入这个插件，Unity版本是2018.2.7f1。在网页后台已经设好了Android和iOS的推送设置。下面是用iOS的包在iphoneX上的结果

参照文档，我先调用了`JPushBinding.Init(gameObject.name);`，然后`JPushBinding.SetAlias(1, "abc")`。等了一会回调也调到了，但参数的json内容是`{"sequence":1,"code":6002}`。根据[文档](https://docs.jiguang.cn/jpush/client/iOS/ios_api/#_165)，重试了几次，还是这个结果。

如果我尝试发送全员广播推送，会报告错误“没有满足条件的推送目标”。

猜测可能是Init时就失败了。有什么建议吗？

**Comment by nikki-nn4** [comment]
我要如何检查Init是否成功呢？
是否可以也提供一个回调，否则“初始化需要一点时间”，何时成功也无法得知

**Comment by JoshLipan** [comment]
以能获取到registrationId为准

**Comment by nikki-nn4** [comment]
大概知道了，需要先调用NotificationServices.RegisterForNotifications

**Comment by tianxiawoyougood** [comment]
> 以能获取到registrationId为准

如果一直获取不到，一直等着吗？我们是订单类的APP，非常影响用户体验。
有没有更好的设计，这个问题好像很多人都遇到，这块的设计体验不好！！！
