### ISSUE TITLE
UnityPluginActivity中的代码作用？

### ISSUE THREAD

**Issue by tiantian20007** [jpush/jpush-unity3d-plugin#3]
https://github.com/jpush/jpush-unity3d-plugin/blob/master/Plugins/Android/src/UnityPluginActivity.java
这个文件中
WindowManager.LayoutParams attr = getWindow().getAttributes();
attr.flags &= (~WindowManager.LayoutParams.FLAG_FULLSCREEN);
getWindow().setAttributes(attr);
getWindow().clearFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);

这4句代码是干嘛的？强行让app不能全屏？
目前我们用该插件打出来的包，游戏多出来黑边

**Comment by lhw5123** [comment]
您好，这段代码在新版本中已经去掉了，十分感谢反馈。 : )
