### ISSUE TITLE
unity支持aar,把android的插件做成aar更方便

### ISSUE THREAD

**Issue by lijinchao2007** [jpush/jpush-unity3d-plugin#7]

**Comment by lhw5123** [comment]
感谢反馈，后面的版本会考虑将 Android 插件做成 aar 的形式的。 : )

**Comment by lijinchao2007** [comment]
你们封装的c#接口，ios和android平台的方式，差异太大了，建议统一一下。JPushBinding的android和ios平台的接口和回调方式，保持一致最好！

**Comment by lijinchao2007** [comment]
android的注册的入口坐在了c#这一层，而ios做在了object－c里面了。android不如加一个application文件，在oncreate里面，注册推送。android接受的推送消息内容，最好把回调函数统一放到JPushBinding中，这样就两边一致了。

**Comment by lhw5123** [comment]
@lijinchao2007 是的，目前确实有这个问题，目前打算是后续来逐步的优化。: )
