### ISSUE TITLE
android 关机后我在web推送 然后开机程序被拉起来后接受到推送会调用Unity的方法报错

### ISSUE THREAD

**Issue by z529943198** [jpush/jpush-unity3d-plugin#9]
关机后JPushBridge.gameObjectName为" " 然后推送消息下来后调用报错
![image](https://cloud.githubusercontent.com/assets/3873275/16112392/b48f9008-33e9-11e6-9724-8d8c572a50ab.png)

**Comment by lhw5123** [comment]
@z529943198 修改了下，可以更新 jar 包再试下。 : )

**Comment by z529943198** [comment]
是更新https://github.com/jpush/jpush-unity3d-plugin/releases/tag/v2.1.1 上面的 还是更新主线上的,你主线上面的JAR 怎么有个com.hevin.jpushunityplugin 还是就是MyReceiver 接收到推送下来的通知 没有改也

**Comment by lhw5123** [comment]
@z529943198  你好，可以先试下 dev 分支里的 jar 包，看看 gameObjectName 是否还是为""。

**Comment by z529943198** [comment]
我试了下还是一样的  
![qq 20160617141053](https://cloud.githubusercontent.com/assets/3873275/16142120/551b50ba-3495-11e6-987b-579bc0c8991f.jpg) 这时候Unity程序还没运行 UnityPlayer.UnitySendMessage 会报错 在调用UnityPlayer.UnitySendMessage之前也应该判断JPushBridge.isQuit吧

**Comment by lhw5123** [comment]
是的，这里确实也应该加一个判断，可以再试下 dev 里的 jar 包。如果还有问题，可以进 [gitter](https://gitter.im/jpush/jpush-unity3d-plugin) 一起讨论下。 : ) 
你的项目被拉起是通过什么来实现的？我这不太好重现这个错误。

**Comment by z529943198** [comment]
项目 应该是被其他程序拉起来的 问题解决了
